#
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#
# Note: CONFIG_ZMK_SLEEP=y is inherited from the shared eyelash_corne.conf.

#EXT POWER
CONFIG_ZMK_EXT_POWER=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# === Studio (Central only) ===
CONFIG_ZMK_STUDIO=y

# === Settings (Central only) ===
CONFIG_SETTINGS=y

# === Split (Central only) ===
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000