CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_PM_SOFT_OFF=y

# Mouse enable
CONFIG_ZMK_POINTING=y

# Uncomment the following line to enable NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
#
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
#
CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_BRT_START=100
